preprocessing:
  n_cv_splits: 5
  max_spellcheck_len: 20
  max_features: 293759
  max_comment_len: 900


embedding:

model:
  clipvalue: 1.0
  num_filters: 4.0
  dropout: 0.5

training:
  batch_size: 32
  epochs: 1
  num_folds: 3
